### PR TITLE
Wuz accessibility action

### LINKED ISSUE #202: 🧹 Consolidate/finalise linting; consider axe Linting and Linkinator
##  Overview
Deque just released [axe linter](https://github.com/marketplace/axe-linter). 
I have done no preliminary research on this, but thought it may be helpful to consider for our set up.

To be explicit, I never see linter tools or automated tests  as a replacement for manual user testing in accessibility. Instead, I see them as helpers.

I wanted to bring this up in the context of the other open PRs and issues revolving around our linting set up (I can't tell which of these are open/closed, but probably helpful for context:

- #139 
- #85 
- #74 
- #88 

## Needs
Ideally I'd like to:
- [ ] Decide whether or not we will use axe Linter
- [ ] Decide whether or not we use a link linter (like [Linkinator](http://npm.im/linkinator))
- [ ] Address and close any open PRs/issues around tests/linting
- [ ] Include notes in our documentation

I think this task is probably best suited for someone with someone who has some familiarity with our database, though it is not necessary. Experience in this sort of area for set up would be great.

cc: @greatislander @ovlb for thoughts!

### PR DESCRIPTION
**Pull request by wuz**

### CODE REVIEW

**Comment by ovlb** [comment]
@wuz Sorry for letting this uncommented for so long. As you do a full Lighthouse run, there are some issues coming up which are not directly tied to a failing accessibility audit. Do you know if it is possible to activate Lighthouse features one by one or should we maybe integrate a solution that is specific to accessibility testing such as [Pa11y](https://pa11y.org/)?

**Comment by wuz** [comment]
@ovlb, yeah! Lighthouse makes it pretty easy to turn of specific rules!

**Comment by ovlb** [comment]
@wuz Great. How do you feel about disabling all but the accessibility checks for now and integrate the other features in a separate PR?

**Comment by tatianamac** [comment]
@wuz Do you still have interest in finishing out this PR? If so let us know if we can do anything to support!

**Comment by wuz** [comment]
@tatianamac hey! Definitely still interested - I am picking my livestreams back up next week and I'll make this the first thing I work on!

**Comment by wuz** [comment]
@tatianamac This action is good to go I think! Looks like it is catching a small problem on one of the pages - I can fix it in this PR if you would like or we can merge this and make a PR to fix that later! Or let me know if you'd like changes!

**Review by tatianamac — APPROVED** [review]

**Comment by tatianamac** [comment]
Blargh, sorry that I lost track of... *gestures*. I went ahead and merged this in, @wuz ! Thank you so much for this PR!

You mentioned a small break. Would you mind either:
1. opening a PR to resolve;
2. opening an issue outlining the issue (lol) so someone else can pick it up?

No worries if you can't do either, but would appreciate if you have the bandwidth!

**Pull request merged**
