### PR TITLE
Fixes broken link to definition of pansexual

### LINKED ISSUE #222: Link to "pansexual" definition is broken on homepage
The link to the definition of `pansexual` from the homepage is broken; it's pointing to `/definitions/pan-sexual/` when it looks like it should be point to `/definitions/pansexual/`. 

Affects both links on the homepage: 
- Pansexual, and 
- Sexual -> Pan

Also impacts link from the `bisexual` definition page

### PR DESCRIPTION
**Pull request by jlealess**
- Fixes broken link to definition of `pansexual` from homepage and from `bisexual` definition page (see [issue #222](https://github.com/selfdefined/web-app/issues/222))

### CODE REVIEW

**Review by ovlb — CHANGES_REQUESTED** [review]
Hey @jlealess,

Thank you very much for this fix. It seems like you checked in a `yarn.lock` file. As we are using NPM to manage our dependencies, can you remove the Yarn lock file? Once this is done, the PR will be merged. Thanks again.

O*

**Comment by jlealess** [comment]
My bad, thanks for catching that, @ovlb ! I've removed it and I'll make sure not to use yarn in any future updates.

**Comment by tatianamac** [comment]
@ovlb Feel free to merge this in once you feel good about it!

(Thank you, @jlealess !)

**Review by ovlb — APPROVED** [review]
Feeling good about this! 🚀

**Pull request merged**
