### PR TITLE
Add plural.md

### PR DESCRIPTION
**Pull request by istx25**
>Denoting more than one entity living in a host body.

I'm also wondering if we should add one for DID but not everyone who is plural identifies or has been diagnosed with that. I could add that definition as well.

### CODE REVIEW

**Comment by tatianamac** [comment]
@non-binary I think this is an awesome base definition! Thank you for contributing!

To your question about DID, I think that it definitely warrants its own definition and possibly cross linking here; a note about how not all plural folks have DID.

Two immediate suggestions come to mind:
1. Could we add some resources that you feel are well-written from plural folks so that readers can go find out more information?
2. I'm wondering if it makes sense to cross-reference the pronoun definition here and/or amend it to be more inclusive of plural identities.

With that said, I think of these as add ons. If you're not feeling up for it, I can open the above items as a new issue, which you or someone else can create a new PR to. I want to do what's most amenable to you!

**Review by tatianamac — APPROVED** [review]

**Comment by istx25** [comment]
Hi @tatianamac,

Thank you for the feedback.

>To your question about DID, I think that it definitely warrants its own definition and possibly cross linking here; a note about how not all plural folks have DID.

Sounds good! I'll add another definition. Is there any particular way to cross link with this project? I've created a new pull request for DID: #231.

>Could we add some resources that you feel are well-written from plural folks so that readers can go find out more information?

I don't know of any resources however I know of some prominent people who are plural in the tech community. Do they count? Not sure if we should link to actual people though.

>I'm wondering if it makes sense to cross-reference the pronoun definition here and/or amend it to be more inclusive of plural identities.

Possibly! Singular they is a thing but so is plural they. I personally use plural they. I've created a pull request editing the neopronouns.md file to add plural they. It's #232.

Thank you and looking forward to hearing from you.

**Comment by tatianamac** [comment]
This is so awesome. Thank you, @non-binary !

>Sounds good! I'll add another definition. Is there any particular way to cross link with this project? I've created a new pull request for DID: #231.

Perfect! I will review that next. And yes, usually we cross-reference definitions by creating a manual new section like this: [minoritised](https://www.selfdefined.app/definitions/minoritised/). (I think that's what you mean, but let me know if I misread.)

>I don't know of any resources however I know of some prominent people who are plural in the tech community. Do they count? Not sure if we should link to actual people though.

Ah yeah, I think that if they've written blogs or public articles about it then we can link to it, but I wouldn't want to put the labour or accidentally out anyone by linking individuals. It feels like a beacon for harassment. One thing we're in the process is creating a "this definition could use more X, Y, Z. Please consider contributing!" to the definitions.

**Comment by tatianamac** [comment]
@non-binary I addressed your questions, but let me know if you want to add more to the definition or for us to merge what's here and to open a new PR/issue later! Up to you.

**Comment by istx25** [comment]
Happy to contribute, @tatianamac. 💃 

>Perfect! I will review that next. And yes, usually we cross-reference definitions by creating a manual new section like this: minoritised. (I think that's what you mean, but let me know if I misread.)

Ah, yes this is what I meant! Thank you. I'll link each of these definitions to each other.

>Ah yeah, I think that if they've written blogs or public articles about it then we can link to it, but I wouldn't want to put the labour or accidentally out anyone by linking individuals. It feels like a beacon for harassment. One thing we're in the process is creating a "this definition could use more X, Y, Z. Please consider contributing!" to the definitions.

Agreed. This is what I was considering too. Some people are public about it but it's definitely an area where someone could be harassed because of it, unfortunately.

**Comment by istx25** [comment]
@tatianamac I've added the read also section here too.

**Comment by tatianamac** [comment]
Thank you, @non-binary ! Would you be okay with us thanking and tagging you from Self-Defined's Twitter when we post this?

**Comment by istx25** [comment]
Plural yes, DID no. :-)

**Pull request merged**
