### PR TITLE
simplify code contributions by fully automating the dev setup.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! :slightly_smiling_face: 

This Pr simplifies code contributions by fully automating the dev setup with gitpod(a free online VS Code like ide). With a single click it will launch a ready to code workspace and automatically:

- clone the self-defined repo.
- install the dependencies.
- start `npm run serve`.

so that anyone interested in contributing to the source code of the site can start away.

You can give a try on my fork of the repo via the link below:

https://gitpod.io/#https://github.com/nisarhassan12/selfdefined

This is how it looks: 
image

### CODE REVIEW

**Comment by tatianamac** [comment]
Awesome! Thanks for setting this up, @nisarhassan12 ! I also love that you're a first-time contributor to our project! ✨

We're working on a few dev environment things, so I'm going to hold off on reviewing this until those are complete. See #74, which I'll consider a block before we review integrating this.

**Comment by nisarhassan12** [comment]
Ok! Thanks :)

**Comment by tatianamac** [comment]
@greatislander @ovlb How do you all feel about this simplification to the dev environment?

This was blocked by the other CI updates we were working on.

**Comment by ovlb** [comment]
Hey @nisarhassan12! Thanks for taking your time to contribute :)

I’ve never used Gitpod before so I can’t comment on the tool itself. Seems decent on first look.

General notes: 
- The only command needed is `npm run serve`
- It does not detect the `.nvmrc` specifying the Node version it should use, would it be possible to integrate? Or can it detect an `engines` field in `package.json`?
- «Wasting time on the setup», as it says in the OP and the Readme draft, is unnecessary hostile wording. I guess that this comes from you being a part of the Gitpod org and aligning with their mission :)

Out of curiosity: Is there a way to activate Prettier/code formatting on save? Just want to understand the capabilities of this tool a little better.

All in all, it can be a viable alternative to cloning locally. Especially as we currently don’t have a workflow to contribute definitions outside of a code editor.

**Comment by greatislander** [comment]
Hi all, I don't have any objections to this and it does lower the barrier to entry. However, I think in terms of facilitating contributions from less technical contributors, the UI still feels very developer-oriented and so it might not have the desired impact.

**Comment by nisarhassan12** [comment]
Thanks, @ovlb :slightly_smiling_face: .
 
> The only command needed is npm run serve

The other command from the Gitpod setup is now removed.

> It does not detect the .nvmrc specifying the Node version it should use, would it be possible to integrate? Or can it detect an engines field in package.json?

I'm working on this.

> Out of curiosity: Is there a way to activate Prettier/code formatting on save? Just want to understand the capabilities of this tool a little better.

activated in https://github.com/tatianamac/selfdefined/pull/88/commits/e42064578b2e99aaeb285d78768d2ab10ef59504 by installing the Prettier VS Code Extension and adding a `settings.json` file.

> Wasting time on the setup», as it says in the OP and the Readme draft, is unnecessary hostile wording. I guess that this comes from you being a part of the Gitpod org and aligning with their mission :) 

Removed in https://github.com/tatianamac/selfdefined/pull/88/commits/fafd7ed360adf88cac53c63734efca55e459f5b1

**Comment by nisarhassan12** [comment]
> Hi all, I don't have any objections to this and it does lower the barrier to entry. However, I think in terms of facilitating contributions from less technical contributors, the UI still feels very developer-oriented and so it might not have the desired impact.

Thanks, @greatislander this Pr is about to simplify code contributions.

 For authoring content Netlify Open Authoring is great and a lot easier.

**Comment by nisarhassan12** [comment]
> It does not detect the .nvmrc specifying the Node version it should use, would it be possible to integrate? Or can it detect an engines field in package.json?

@ovlb fixed in https://github.com/tatianamac/selfdefined/pull/88/commits/40c9ed8124757cac75b1d6d6dbf75bfee2655942

**Comment by tatianamac** [comment]
@ovlb @greatislander  Is there anything else we'd like to see here?

**Comment by ovlb** [comment]
@tatianamac I’ll have a final look tomorrow. 

And, @nisarhassan12, sorry for the radio silence here.

**Comment by nisarhassan12** [comment]
> It does not detect the .nvmrc specifying the Node version it should use, would it be possible to integrate? Or can it detect an engines field in package.json?

> @ovlb fixed in 40c9ed8

Sorry this is not fixed yet I initially thought it was but It turns out to be false.
The default Node version in Gitpod is `12.16.3` and the setup seems to be working fine.

I will try to figure this out. Thanks.

**Comment by nisarhassan12** [comment]
@tatianamac Thanks! would you please tell why you closed this PR?

**Comment by tatianamac** [comment]
@nisarhassan12 Because I ported the repo over to a new org and renamed the main branch from `master` (which was problematic) to `prod`, I think you'll need to reopen it and make a PR to the new main branch (`prod`)

**Comment by nisarhassan12** [comment]
Ok. Thanks.

**Pull request closed without merging**
