### PR TITLE
Add definition for the word barbarian

### PR DESCRIPTION
**Pull request by codeAbul**
- Adds definition for the word barbarian including the impact, usage tip, issues and sources. 

( Side note: This is my first ever contribution to a OSS project. Thanks to @tatianamac for being so welcoming, giving the confidence that OSS is not the domain of cishet white bois alone )

### CODE REVIEW

**Comment by codeAbul** [comment]
Sorry, getting build failures. Will fix and raise again!

**Comment by ovlb** [comment]
Hey Abdul,

Welcome to the community. 

The build failure is my fault and might be hard to debug. I made it so that Eleventy only checks for the lowercase string. 🤦 I will open a fix PR to make this less faulty. 

For now, you need to specify the `level` of the flag in lowercase. You [can find working examples](https://www.selfdefined.app/documentation/front-matter/#flag) in the documentation.

One further suggestion: You can add your sources in the front matter part, too. They will be auto-compiled into a list during build time. Check the [further reading docs](https://www.selfdefined.app/documentation/front-matter/#further-reading) for more information.

**Comment by codeAbul** [comment]
@ovlb hello Oscar, thank you for the response. I appreciate it. Fixed it. Now I am able to build. Also moved the sources to front matter. Will raise a PR. Thank you for the assistance ( I haven't worked with nunjucks/eleventy before ! I need all the help I can get :) )

**Comment by tatianamac** [comment]
Thank you @codeAbul and @ovlb ! I appreciate you both!

**Pull request closed without merging**
