### PR TITLE
Removes .nvmrc; gitignores .nvmrc and .tool-versions

### PR DESCRIPTION
**Pull request by mpcsh**
See #404 for context, specifically [this comment](https://github.com/selfdefined/web-app/pull/404#issuecomment-834756503) and [this comment](https://github.com/selfdefined/web-app/pull/404#issuecomment-835721761)

### CODE REVIEW

**Comment by ovlb** [comment]
Hey. We should not remove these files, as they configure different tools to use the correct NPM version. To avoid errors in the build we should make sure that all contributors use the same NPM version not configure them as they see fit.

**Comment by ovlb** [comment]
For context: we had some issues with folx using NPM versions that were all over the place and dependencies that failed in these versions. Since we added the tool files to have canonical versioning.

**Review by ovlb — CHANGES_REQUESTED** [review]
See comments.

**Comment by mpcsh** [comment]
Fair enough! See #412

**Pull request closed without merging**
