### PR TITLE
Adds alertbox to definition pages

### LINKED ISSUE #141: 🗃️ Build "revise term" alert box
## Overview
Build a component that follows each definition that encourages readers to submit revisions if needed.

Recommendation would be to build a separate `.njk` block that can be called by the definition template.

## Design
Threw together a rough wireframe. It's not in the correct fonts but should give you an idea of the general structure.

Reach out with any questions!

### PR DESCRIPTION
**Pull request by jlealess**
- creates a new alertbox component to encourage users to contribute
- adds alertbox component to definition page template to ask users improve existing definitions

### CODE REVIEW

**Comment by tatianamac** [comment]
@jlealess ! Awesome work on this! I think we can expand this later to include the Edit on GitHub feature Oscar mentioned.

In the meantime, consider this is PR approved once you update the branch to align with the most current version. 

Once this is merged in, would it be okay to thank you on Twitter?

**Review by tatianamac — APPROVED** [review]

**Comment by jlealess** [comment]
@tatianamac I'm updating the branch to align with the most current version of master today, but I'm seeing a merge conflict; does this alert box go before or after the content warning that's been added to the definition template? 

And yes, you can thank me on Twitter; thank you for helping me through this!

**Comment by tatianamac** [comment]
Good question. I think below for now is good. Long term the larger, bottom content warning box is going to go away. The top content warning will lead you to another page, I think.

**Comment by tatianamac** [comment]
@jlealess  Do you mind opening a new PR? Unfortunately when I renamed the branch it force closes all the open PRs. Thank you!

**Pull request closed without merging**
