### PR TITLE
✏️ Configure Netlify CMS for Open Authoring

### PR DESCRIPTION
**Pull request by greatislander**
This PR completes work towards #95 by configure Netlify CMS to edit all fields as documented in [Front Matter](https://github.com/selfdefined/web-app/blob/prod/11ty/documentation/front-matter.md).

It includes:

- [x] Test and refine Netlify CMS interface for definition submission.
- [x] Dynamic previews of rendered definitions in Netlify CMS.

Merging will not immediately enable open authoring contributions. This will necessitate some coordination with the project maintainers.

### CODE REVIEW

**Comment by greatislander** [comment]
Hi @tatianamac and @ovlb, I've finally had some time to pick #95 back up and have made some progress in terms of configuring all of the fields for Netlify CMS (as well as merging the most recent updates from the `prod` branch). You should be able to test out the new UI as per my earlier instructions here: https://github.com/selfdefined/web-app/issues/95#issuecomment-612263183

**Comment by tatianamac** [comment]
Thank you, @greatislander ! I have pinged folks in the [Slack community](https://join.slack.com/t/selfdefined/shared_invite/zt-fczgm8b6-8ZZgHvLutNDXo~NjwaL7Iw) to see if someone can review in my stead. If you're interested in joining, we welcome you, but no pressure ofc!

Stay tuned for more edits. 👍🏽

**Comment by tatianamac** [comment]
@greatislander Hi! Are you interested in/have bandwidth for finishing out this PR? What would be most helpful for you to move forward if so?

**Comment by greatislander** [comment]
@tatianamac Yes! I'll update with changes from prod and get back to you shortly :)

**Comment by tatianamac** [comment]
@greatislander : No rush at all on my side, but please let us know when this is ready to review. :)

**Comment by greatislander** [comment]
@tatianamac This is done, pending your feedback! Let me know if you'd like any other info to test and review. As a reminder, the functionality can be tested against my fork by logging in [here](https://selfdefined-open-authoring.netlify.app/admin/) with one's GitHub account.

**Pull request closed without merging**
