### PR TITLE
Fix ableist filename

### LINKED ISSUE #244: Ableist language file is misspelled as 'ablelist-language.md'
(able**l**ist, shouldn't have an l? Not 100% sure but probably a mistake.)

### PR DESCRIPTION
**Pull request by CanadaHonk**
Fixes #244.

### CODE REVIEW

**Review by tatianamac — APPROVED** [review]
🚀 LGTM

**Comment by CanadaHonk** [comment]
Also @tatianamac, is it best to open an issue, then a PR or just open a PR about something? (Misspellings, adding new definitions specifically).

**Comment by tatianamac** [comment]
@Oj18 Great question! Generally, my rule is:

**Open PR**
- Correct misspellings
- Fix broken links
- Add definitions/nuance/translations to words that exist on the site already but are undefined/partially defined/could use more nuance
- Resolve issues that already exist

**Open Issue**
- Concern or question around a term that you don't have clear prescriptive feedback around
- Adding a new term that is not yet listed (with or without definition)

Hopefully that's helpful. Let me know if you have more specific questions than that.
 (I have ideas of a FAQ in the works; this inspires me to open a PR about it.)

**Comment by CanadaHonk** [comment]
Cool, thanks @tatianamac!

**Pull request merged**
