### PR TITLE
⚙️ Add stylelint and base configuration (see #74)

### PR DESCRIPTION
**Pull request by greatislander**
This PR adds stylelint, with a basic configuration as described in https://github.com/tatianamac/selfdefined/issues/74#issuecomment-588279960. It also applies the stylelint rules to master branch SCSS files.

### CODE REVIEW

**Comment by ovlb** [comment]
Thanks for this :)

**Comment by tatianamac** [comment]
@greatislander I think I might have messed this up by approving your other PR. Are you able to take a look at this conflict?

**Comment by greatislander** [comment]
@tatianamac Fixed! And I've added automatic linting (with `--fix`) for Sass files to the pre-commit hook. Should be merge-ready now.

**Comment by ovlb** [comment]
I put my sea( shel)l of approval on this. 🐚

**Pull request merged**
