### PR TITLE
Update biseksueel.md

### PR DESCRIPTION
**Pull request by frederikprijck**
I wanted to update the dutch definition of bisexual because:

- een geslacht reads as "a gender"
- één geslacht reads as "one gender"

Being attracted to more than a gender might be more like pansexual, whereas bisexuality is more about more than "one gender" (which is also the english definition in this repo).

### CODE REVIEW

**Comment by tatianamac** [comment]
@Primigenus @sophieschoice Would either/both of you care to weigh in on this suggestion?

(I wish I could speak Dutch to have opinions 💅🏽)

**Comment by Primigenus** [comment]
Yes, I actually recommended this change [in the previous PR](https://github.com/tatianamac/selfdefined/pull/87#discussion_r385295318), but I guess it was overlooked.

**Comment by tatianamac** [comment]
Thank you, @Primigenus . @frederikprijck do you have thoughts on "geslacht" v. "gender" here?

**Comment by frederikprijck** [comment]
I think using `Gender` instead of `Geslacht` makes sense as well, especially looking at the english definition.

**Comment by sophieschoice** [comment]
Agreed!

**Comment by frederikprijck** [comment]
I will update this PR asap and fix that as well!

**Comment by frederikprijck** [comment]
Updated!

**Pull request merged**
