### PR TITLE
📝 Adds alt words to 'dude'

### PR DESCRIPTION
**Pull request by silvestrijonathan**
This PR introduces some alternative words to dude to use in conversation. 

I attempted to divide the words by "expression" and "person", but I found I couldn't nest under `alt_words` properly.

### CODE REVIEW

**Comment by tatianamac** [comment]
Awesome, thanks for submitting, @silvestrijonathan !

Re: separate uses:
That's a helpful use case that I will open an issue to fix! It'd be helpful to show 1:1 replacements when a word means a specific thing.

**Comment by tkshill** [comment]
Hey @silvestrijonathan,

I was also working on a list of alt words for dude but I hadn't even considered its use as an expression/exclamation. That's a good catch. Most of my list you already covered, but may I also suggest the following terms to your list?

- fam
- folks
- pal
- buddy

**Comment by silvestrijonathan** [comment]
Hey @tkshill !

Thanks for getting in touch! I think these are solid additions and I am happy to include them. What do you think, @tatianamac

**Comment by silvestrijonathan** [comment]
@tatianamac "Pal" and "buddy" do sometimes give me a little bit of pause. I think a "Caveat" section, with this listed, is a great idea.

Given the state of things right now, I would like to wait until after the weekend to pick this back up, if that's alright.  But I can add these discussed items and then ping you again.

**Comment by silvestrijonathan** [comment]
@tatianamac @tkshill I've added those items as we've discussed.

**Comment by tatianamac** [comment]
Thank you, @silvestrijonathan ! Would it be okay with you if I thanked you from the Self-Defined Twitter Account?

**Comment by silvestrijonathan** [comment]
Sure thing @tatianamac!

**Pull request merged**
