### PR TITLE
Feature/content warning guidelines

### PR DESCRIPTION
**Pull request by MatthewShields**
Addition of content warning guidelines elements to the definition page template.

Warning pages:

image

image

Avoid pages:

image

image

### CODE REVIEW

**Comment by tatianamac** [comment]
@MatthewShields ! OMG! AMAZING! 

I think I confused you a bit here, so I'm sorry for that. The content warning should continue and maintain the top styling. In the future, when we build out warnings, I think your secondary styling makes sense (for example, when we discuss slurs).

Is it possible to only apply the top styling for now? Thank you!

Also, could you please remove the [ ] around the word? Thank you!

Once this is merged in, is it okay if I thank you from the Self-Defined Twitter?

**Comment by MatthewShields** [comment]
@tatianamac No problem at all, I'm really enjoying my first contributing experience :)

I am however really sorry that I am going to have to ask just to make sure what it is you are after in terms of the styles just to make sure that I am really clear. (Sorry I will get better at this!)

For the top styling are you wanting:

A:
image

B:
image

For the bottom styling are you wanting:

A:
image

B:
image

C:
Remove styling

I have committed your other suggestions too - love that you can do that directly from the reviews! We don't use github but bitbucket server at work so thats a new one to me 🥳

Also that would be grand if you posted on Twiiter - thanks!

**Comment by tatianamac** [comment]
B on both, please and thank you! No apologies, I appreciate you being thorough.

And yes, that feature is so, so nice! I try to only use it when it's a noodle-y semantic thing and not micromanaging someone's code!

I'm very excited to promote this feature as it ties in with a definition I have pending for suicide (which definitely requires a content warning), so I'll be able to promote both in short order.

**Comment by MatthewShields** [comment]
Great in which case I believe that this PR is ready to be merged :)

I'm really happy to have helped even in this small way.

Please let me know if there is anything further that you need me to do (I think I have everything on my side as I have done the PR to master)

**Pull request merged**
