### PR TITLE
fixed the typo in the README.md for Contributor Covenant spelling

### LINKED ISSUE #249: Readme.md typo for Code of Conduct section
Need to change `Contributor Convenent` to `Contributor Covenant` to reflect appropriate spelling

### PR DESCRIPTION
**Pull request by JGibson2019**
Addresses issue #249 

Updating the spelling to say "Contributor Covenant" for consistency with other areas of the documentation

### CODE REVIEW

**Comment by tatianamac** [comment]
Thanks for submitting this, @JGibson2019 ! Do you happen to know why your package-lock.json generated so many changes? I would expect that this change would only change the README.md file.

**Comment by JGibson2019** [comment]
> Thanks for submitting this, @JGibson2019 Jacqueline Gibson FTE ! Do you happen to know why your package-lock.json generated so many changes? I would expect that this change would only change the README.md file.

Thanks @tatianamac When I ran the build commands recommended in the documentation, and ran npm audit fix, I believe that caused the updates to the package.json and package.json lock. Will that block the PR getting merged in?

**Comment by JGibson2019** [comment]
> > Thanks for submitting this, @JGibson2019
> >             
> >             Jacqueline Gibson
> >             FTE Jacqueline Gibson FTE ! Do you happen to know why your package-lock.json generated so many changes? I would expect that this change would only change the README.md file.
> 
> Thanks @tatianamac When I ran the build commands recommended in the documentation, and ran npm audit fix, I believe that caused the updates to the package.json and package.json lock. Will that block the PR getting merged in?

Just went ahead an reverted the commit that updated the package.json files and just added the README.md updates

**Comment by ovlb** [comment]
@JGibson2019 Thanks! As general guidance, we try to keep pull requests as side-effect free as possible. By running `npm audit fix` the lock file got updated. Doing so is not wrong, but including this here broadened the scope of the PR, making it harder to see what changed (or maybe if one of these lock file updates broke something completely unrelated).

Also, can you tell me which npm version you had running when you ran `npm audit fix`? Asking because `optional: true` has been added to a lot of packages. 

I’ll update the documentation to clarify the usage of the audit command and when (or when not) it should be part of a PR.

**Review by ovlb — APPROVED** [review]
🐚

**Comment by JGibson2019** [comment]
> @JGibson2019 Jacqueline Gibson FTE Thanks! As general guidance, we try to keep pull requests as side-effect free as possible. By running `npm audit fix` the lock file got updated. Doing so is not wrong, but including this here broadened the scope of the PR, making it harder to see what changed (or maybe if one of these lock file updates broke something completely unrelated).
> 
> Also, can you tell me which npm version you had running when you ran `npm audit fix`? Asking because `optional: true` has been added to a lot of packages.
> 
> I’ll update the documentation to clarify the usage of the audit command and when (or when not) it should be part of a PR.

I am running npm version 6.14.4

**Pull request merged**
