### PR TITLE
Adding an 'about' page

### PR DESCRIPTION
**Pull request by ivana-mcconnell**
This aims to address https://github.com/tatianamac/selfdefined/issues/129. With respect to the content on this page, I can be a little...verbose, so if it needs condensing, let me know. Any and all comments on accuracy, grammar, arrangement, etc. are appreciated! 

**Changes:**
 
* The 'About' page content, as outlined in the issue above: the backstory, notes on language, content warnings, usage/licensing, OSS, and future plans. 
* Adds the layout for the about page, as well as a link in the base layout so that 'About' appears in the side nav
* Adds a 'Learn more' link on the index page, so users can navigate to the 'About' page from the index. 

**Questions:** 
1. For @tatianamac: I wasn't sure what the following part of the 'future plans' meant. Can you describe it for me a bit more? 
> This would include the ability to use parameters, so that someone can connect multiple words they use together, to help clear up how they define themselves. For example, ?disabled+pan+Indigenous. Creating such a strand easily would allow people to link in email signatures, Twitter bios, etc. 
2. I noticed that, on pages with longer content, the side nav is pushed to the bottom (see image below). This feels like it should be closer to the top, right under the Self-Defined heading and subtitle.

image

### CODE REVIEW

**Comment by tatianamac** [comment]
@ivana-mcconnell  Because I ported the repo over to a new org and renamed the main branch from master (which was problematic) to prod, I think you'll need to reopen it and make a PR to the new main branch (prod). Reach out to the Slack channel for help. 🙏🏽

**Comment by tatianamac** [comment]
@ivana-mcconnell  Are you able to re-open this PR as a new PR so we can continue progress? Sorry about that!

**Comment by tatianamac** [comment]
@ivana-mcconnell Would you mind reopening this issue? I'd love to have you help me if you still have bandwidth (but recognise it's been a ridiculous year!). Even if you're no longer to help, I'd love to honour all the great work you've put into this already. Thanks!!!

**Comment by ivana-mcconnell** [comment]
@tatianamac I don't seem to have the option to do so! All I can do is delete the branch.

**Comment by tatianamac** [comment]
@ivana-mcconnell Ah, I should have been clearer! Are you able to push up the code from your local branch to a new remote branch? So sorry for the pain!

**Comment by ivana-mcconnell** [comment]
@tatianamac argh, I don't have it locally anymore and my Github skills are admittedly limited. If you'd like to use any of the text I wrote, you're welcome to grab it from the commit. Sorry about that!

**Pull request closed without merging**
