### PR TITLE
WIP: 📄 Add Detail Pages for Definitions

### LINKED ISSUE #53: 📄 Add Detail Pages for Definitions
As the site grows, the homepage gets more and more crowded and impossible to scan. I think we should link to detail pages for single definitions (e.g. `/definitions/crazy` instead of `#crazy`).

Edit: I keep track of this issue and update the to-do list in #75. So have a look there for the current status

### LINKED ISSUE #60: Word definition links need focus management
## Problem
Clicking on a definition scrolls the user to that definition, but:
- Keyboard focus remains on that link, which could confuse keyboard users and especially screen-reader users
- Because multiple definitions appear close together, it is not always obvious where a sighted user's attention should go
## Proposed solution
- Use tabindex and javascript to move focus to the heading where a word is defined
- Apply a gentle, temporary highlight to the wrapper behind the definition, so sighted users know where to look
## Further reading
This codepen on [drawing attention to internal focus](https://codepen.io/dengeist/pen/vYOEXgg) utilizes a pattern that I think would be helpful here.

### PR DESCRIPTION
**Pull request by ovlb**
Declutter the homepage and create a deeper site structure by moving definitions into their own template. 

## To Do

- [x] Create sane markup structure for detail pages
- [x] Change link for definitions to `/definitions/{{word}}/`
- [x] Remove definitions from home page
- [x] Add next/previous links to bottom of detail page
- [x] Add complete site title (currently only the word, add « | Self-Defined»)
- [x] Discuss & implement design
- [x]  Add `301` redirects for existing in-page word links (`301` don’t work, handled client-side)
- [ ] 404 page
- [ ]  Screenreader testing

## Linked Issues

resolves #53, fixes #60

### CODE REVIEW

**Comment by ovlb** [comment]
@tatianamac Netlify redirects don’t seem to work for fragment identifiers (or whatever the actual name of in-page-links is). I’ve added one for `/#ok-hand`, but the index page is always loading. I solved this through an inline script for now (https://github.com/tatianamac/selfdefined/pull/75/commits/f3bf666dbe1bfa38d3405a6a91da296ac669cbe7). Might not be the best solution, but it is one.

Other than that, it’s slowly approaching the finish line. The design, especially mobile, is sub-par so far. I could iterate over this for a bit. Or do you have ideas/wishes?

**Comment by tatianamac** [comment]
**Redirects**
It looks like according to this example it should be (though I imagine you already thoroughly researched this)?
https://docs-docs.netlify.com/docs/docs/redirects.html
If we can't resolve it, I'm happy to put a word out on Twitter to see if anyone can figure it out. We can also create a separate issue to ask for help.

**Design**
I have a few suggestions to improve the design.
- [ ] Widen definition column and its elements. It's a bit hard to read and awkwardly placed.
- [ ] Improve typographic consistency.
- update header font
- collapse part of speech
- make part of speech font consistent with production site
- [ ] Remove 'browse' label. For navigability I think we can have that be announced by screenreaders but not necessarily display.
- [ ] Fix mobile spacing for next/previous headers (currently very tight)

To show you very roughly the desired outcome:
Adjusted design with wider columns and consistent type

Below are the css changes I made. At some point we'll want to open a new issue to properly write out the full `_definition` sass partial and refine its design further.

```
:root {
- --auto-grid-min-size: 17rem; 
+ --auto-grid-min-size: 47rem; 
}
.definition {
- max-width: 38rem;
}
h1, h2, h3, h4 {
- margin-top: 1em;
- margin-bottom: 0.5em;
}
.definition__header {
- margin-bottom: 3rem;
}
.definition-content__signal {
- border-top: 0.25rem solid var(--word-signal-color);
+ border-top: 0.15rem solid var(--word-signal-color);
+ width: 100%;
}
.definition-content__speech {
+ font-weight: 500;
}
.definition__header {
+ font-family: orpheuspro,Palatino,Times,serif;
}
.main-headline {
+ font-family: orpheuspro,Palatino,Times,serif;
+ margin: 0;
}
```

Hope this is helpful—thank you so much for making this big move! I feel like the dictionary is growing up 😭💙

**Comment by ovlb** [comment]
>  It looks like according to this example it should be (though I imagine you already thoroughly researched this)?

*blushing me sits in front a screen

Actually, I added the redirects to the `netlify.toml` config file as I used this with another project. Will try a `_redirects` file. 


Thanks for the design notes. Will implement them!

One thing: The enlarged font size for the basic definition makes for very short lines on mobile devices. I wonder if we should tone it down on smaller screens and only use it as a design element once the viewport has a minimum width of {tbd} pixels.

**Comment by tatianamac** [comment]
> One thing: The enlarged font size for the basic definition makes for very short lines on mobile devices. I wonder if we should tone it down on smaller screens and only use it as a design element once the viewport has a minimum width of {tbd} pixels.

Yes.  I wonder if this work can be done not as part of this issue but instead first as part of #47.  @codeAbul has graciously agreed to take on (Thank you, @codeAbul !). I'm hoping they can consider this challenge as part of that work. Does that work for you?

**Comment by ovlb** [comment]
@tatianamac 

> Yes. I wonder if this work can be done not as part of this issue but instead first as part of #47. @codeAbul has graciously agreed to take on (Thank you, @codeAbul !). I'm hoping they can consider this challenge as part of that work. Does that work for you?

That works for me :)

I’ve updated the design (finally). It feels like mostly done now. I feel do some deeper cross-browser and screen-reader tests tomorrow. Maybe you and @dengeist could also review the site structure as a whole now that it is mostly stable?

**Comment by ovlb** [comment]
@tatianamac I also tried to merge our Sass infrastructure changes together. Maybe you could have another look if I missed/broke something.

**Comment by tatianamac** [comment]
@ovlb  Thanks so much for this! It improves everything a lot. The Sass changes are fine with me; it's always fun to see how different people organise their Sass files. 😅

A few things:
- [ ] Definition links no longer work as they're still linking to the anchor tags
- [ ] Definition post pages do not call the CSS, so they're rendering unstyled

Once those two main issues are resolved I think this is ready to close.

**Comment by ovlb** [comment]
@tatianamac

 I thought I replaced all hashes. Where did you find some? 

I want to do a round of screen-reader testing on Monday. Other than that I, took, think we have a nice set of detail pages now :)

**Comment by tatianamac** [comment]
From the main page (I couldn't track where the links themselves are generated from 🙈.) 

I saw that you wrote a redirect, which I know will handle external links, but I imagine we'd just want to fix it on the main page?

Also is it something on my end where the CSS isn't rendering for single definition pages? Does that work for you?

Otherwise agreed that this is a lovely progress for the little dictionary. 😢 ❤️

**Comment by ovlb** [comment]
Strange, they should be. And are also on the latest deploy preview. https://deploy-preview-75--selfdefined.netlify.com/ Do you maybe have an old version in your cache?

**Comment by tatianamac** [comment]
😭  I don't know what's wrong with my install but I trust you. As long as those issues are handled I think we're good after SR testing.

**Comment by ovlb** [comment]
Is your dev server running since a while? Eleventy does not recognise changes to already registered shortcodes/filters without ending and restarting the script. 

Note to self: add a note regarding this in the dev documentation. 

The corresponding commit is https://github.com/tatianamac/selfdefined/commit/ea3420decd6141631d85586bd004786834a67ad8 (unit test buried in here https://github.com/tatianamac/selfdefined/commit/fa50c6d46c0c73ba7637ae7324bf3dba70b4e798)
Links to definitions inside of other definitions have been replaced with this one https://github.com/tatianamac/selfdefined/commit/391f7e4ceb5e57eb223a866eceedcc283f070046

One thing I wanted to investigate: currently Eleventy generates html files for undefined words. I would like to disable this to avoid having empty pages on the server.

**Comment by ovlb** [comment]
What I mean with restarting: CTRL+C to stop the server completely and manually starting the script again

**Comment by codeAbul** [comment]
Dear @tatianamac &  @ovlb , 

I have been going through a tough period mental health wise since a week or so vis-a-vis anxiety due to some life changes, so my development work on fluid type scale has been halted. I am not sure when I could get back on it. If someone else has time, please feel free to work on it. I am really sorry! I hope to get better soon and contribute to the project again. 

Love, 
Abul

**Comment by ovlb** [comment]
Dear @codeAbul, 

Please don’t feel sorry because of this :) We (I think I can speak for Tatiana in this case, too) are immensely grateful for your contributions so far. And the most important thing right now is that you focus on getting better again. 
I don’t know if I can do anything, but if so please let me know.

Sending all the strength and calm breaths of the world to you and looking forward to you coming back when you feel like it,
Oscar

**Comment by tatianamac** [comment]
@codeAbul Yes, absolutely. Please take care of you first and let us know if we can do anything to help from afar! We'd love to have you back if you're able and willing in the future but you are most important!

**Comment by tatianamac** [comment]
I'm not sure what happened but this appears to be resolved now, despite me taking the same steps as yesterday. 🙃

The only thing I noticed for right now is that I think that flag updates #79 aren't coming across yet. Let me know if that's just on my end. 🙈

**Comment by ovlb** [comment]
Yay, magic. I didn’t merge master, so they were missing. Should be integrated now!

**Pull request merged**
