### PR TITLE
Updated intro paragragh (definition)

### PR DESCRIPTION
**Pull request by asostechnix**
Updated the intro paragragh based on the ICD-11 (the international equivalent of the US's DSM) for the following reasons:
  * The previous text referred only to ADHD in children
  * The previous text used the word 'disinterested' when I suspect the intended meaning was 'uninterested' but the sentence strucutre also needed a little tweaking
  * The previous text defined attention based on what was interesting or not but that's not quite accurate 
  * The previous text only summarised focus (attention) but didn't summarise the other components of ADHD which are impulsivity and hyperactivity.

Added reading link to the ICD (for international readers where the DSM is not used)

### CODE REVIEW

**Comment by tatianamac** [comment]
Thank you for submitting this @asostechnix ! I have shared it with the community to get additional sensitivity reads. We'll reach back out with any feedback!

**Review by jvbreen1 — APPROVED** [review]

**Comment by jvbreen1** [comment]
Thank you for the updates! I hadn't noticed that I was referring only to children in that definition - good catch.

**Review by tatianamac — APPROVED** [review]
Approved! Thanks for the thoughtful changes and additions.

**Comment by tatianamac** [comment]
@ asostechnix Thank you and congrats on your first PR with us! We really appreciate you contributing and hope you'll come back!

**Comment by asostechnix** [comment]
Thanks for the welcome! Happy to be able to contribute.

**Pull request merged**
