### PR TITLE
⚙️ Add linting and CI infrastructure

### PR DESCRIPTION
**Pull request by greatislander**
This PR runs lint and test commands in a pre-commit hook when JS files are staged (using husky and lint-staged), and adds a GitHub Actions workflow which runs lint and test commands. This is a starting point for addressing #74, and could be merged as-is or once other pieces of the linting/testing infrastructure are in place and ready to be integrated (e.g. Stylelint).

One thing that I didn't do that might be worth considering was set the lint command to run with `--fix` to automatically address any issues that eslint + Prettier can resolve on their own. This could be "a way to apply the formatting configured through the tools above for contributors who are not able to set up an advanced dev workflow on their machines" as per @tatianamac in https://github.com/tatianamac/selfdefined/issues/74#issue-565725608. Let me know if you think that would be a good next step.

GitHub Actions results on my fork: https://github.com/greatislander/selfdefined/runs/455516486?check_suite_focus=true

### CODE REVIEW

**Comment by tatianamac** [comment]
LGTM!

**Comment by greatislander** [comment]
I've added the `--fix` flag to the eslint hook.

**Comment by tatianamac** [comment]
Thank you so much, @greatislander! 🎉

**Comment by greatislander** [comment]
My pleasure!

**Comment by greatislander** [comment]
I'm going to update #92 with these changes, so it will include auto-fix on commit.

**Comment by UnsnappedKhan8** [comment]
> This PR runs lint and test commands in a pre-commit hook when JS files are staged (using husky and lint-staged), and adds a GitHub Actions workflow which runs lint and test commands. This is a starting point for addressing #74, and could be merged as-is or once other pieces of the linting/testing infrastructure are in place and ready to be integrated (e.g. Stylelint).
> 
> One thing that I didn't do that might be worth considering was set the lint command to run with `--fix` to automatically address any issues that eslint + Prettier can resolve on their own. This could be "a way to apply the formatting configured through the tools above for contributors who are not able to set up an advanced dev workflow on their machines" as per @tatianamac in [#74 (comment)](https://github.com/tatianamac/selfdefined/issues/74#issue-565725608). Let me know if you think that would be a good next step.
> 
> GitHub Actions results on my fork: https://github.com/greatislander/selfdefined/runs/455516486?check_suite_focus=true

Think your referring to me

**Pull request merged**
